init:
 - appveyor version
 - sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
 - sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
 - sh: |
    # Only use colors if connected to a terminal
    if [ -t 1 ]; then
      RED=$(printf '\033[31m')
      GREEN=$(printf '\033[32m')
      YELLOW=$(printf '\033[33m')
      BLUE=$(printf '\033[34m')
      BOLD=$(printf '\033[1m')
      RESET=$(printf '\033[m')
      NC=$(printf '\033[m')
    else
      RED=""
      GREEN=""
      YELLOW=""
      BLUE=""
      BOLD=""
      RESET=""
      NC=""
    fi
test_script:
 - sh: |
    function global_json() {
        echo "{
      \"sdk\": {
        \"version\": \"$1\"
      }
    }"
    }
    WELCOME="^Welcome to .NET Core"
    for ver in $(dotnet --list-sdks|cut -f1 -d' '); do
        TMP_DIR=$(mktemp -d)
        pushd  "${TMP_DIR}"
        global_json ${ver} >global.json
        OUTPUT=$(dotnet new console)
        while read -r line; do
          if [[ $line =~ $WELCOME ]]; then
            echo "${RED}'$ver' is not pre-heated!${NC}"
            return 2
          fi
        done <<< "${OUTPUT}"
        popd &&
        rm -rf "${TMP_DIR}"
    done
 - sh: ls -ltra "$HOME/.dotnet/"
 
build: off
